name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libffi-dev libssl-dev ccache
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK with Buildozer
        run: |
          # Pré-création des répertoires d'acceptation de licences
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          echo -e "2433373574b44d1528f65d33db1509291ee07e0e\n89330d322475b11d56e1ce783dcd212fc6221619\nd56f5187479451eabf01fb78af6dfcb131a6481e" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo -e "84831b94fe6460066657176d450d700efe0a9272" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license
          
          # Lancement du build en répondant automatiquement "yes" à toutes les invites
          yes | buildozer --debug android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PocketSOC-APK
          path: bin/*.apk
          
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PocketSOC-APK
          path: bin/*.apk
          
