name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build APK with Buildozer Action
        uses: Artemis-Sera/buildozer-action@v1
        with:
          workdir: .
          buildozer_cmd: buildozer --debug android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PocketSOC-APK
          path: bin/*.apk
          
